name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  who:  
    description: 'should be say hello'
    required: true
  build:
    description: 'should the project be builded'
    required: true
  run:
    description: 'should the project be runned'
    required: true
  dir:
    description: 'working directory'
    required: true
runs:
  using: 'node16'
  main: 'src/index.js'