on: [push]

jobs:
  CI-CD:
    runs-on: ubuntu-latest
    name: WTF!!!!
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker build and push
        run: |
          docker build -t yesinaleksey/website .
          docker push yesinaleksey/website
      - name: Docker run
        run: |
          docker run -d yesinaleksey/website
      
