on: [push]

jobs:
  CI-CD:
    runs-on: self-hosted
    name: WTF!!!!
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-buildx-action@v2
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker build and push
        run: |
          docker build -t yesinaleksey/website .
          docker run -d -p 7777:80 yesinaleksey/website
      
